import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Travel</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>Добро пожаловать в наше тревел-агентство!</h1>
            <p>Мы предлагаем широкий выбор туров по всему миру и уникальные услуги, которые помогут сделать ваше
                путешествие незабываемым!</p>
            <button>Подобрать тур</button>
        </>
    )
}
